// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace McjCoderOrg.HookTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "pre-commit")]
    [global::Xunit.TraitAttribute("Category", "Integration")]
    public partial class Pre_CommitHookValidationFeature : object, global::Xunit.IClassFixture<Pre_CommitHookValidationFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "pre-commit",
                "Integration"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Pre-commit hook validation", "    As a developer\r\n    I want the pre-commit hook to enforce quality standards\r\n" +
                "    So that code quality is maintained before commits", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PreCommitHook.feature"
#line hidden
        
        public Pre_CommitHookValidationFeature(Pre_CommitHookValidationFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
    #line hidden
#line 8
        await testRunner.GivenAsync("I have a git repository with hooks configured", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/PreCommitHook.feature.ndjson", 7);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Block direct commits to main branch")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Pre-commit hook validation")]
        [global::Xunit.TraitAttribute("Description", "Block direct commits to main branch")]
        [global::Xunit.TraitAttribute("Category", "branch-protection")]
        public async global::System.Threading.Tasks.Task BlockDirectCommitsToMainBranch()
        {
            string[] tagsOfScenario = new string[] {
                    "branch-protection"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Block direct commits to main branch", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 12
        await testRunner.GivenAsync("node_modules directory exists", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 13
        await testRunner.AndAsync("I am on the \"main\" branch", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
        await testRunner.WhenAsync("I attempt to commit", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
        await testRunner.ThenAsync("the hook should fail with exit code 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 16
        await testRunner.AndAsync("the output should contain \"Direct commits to main are not allowed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Allow commits on feature branches")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Pre-commit hook validation")]
        [global::Xunit.TraitAttribute("Description", "Allow commits on feature branches")]
        [global::Xunit.TraitAttribute("Category", "branch-protection")]
        public async global::System.Threading.Tasks.Task AllowCommitsOnFeatureBranches()
        {
            string[] tagsOfScenario = new string[] {
                    "branch-protection"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Allow commits on feature branches", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 19
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 20
        await testRunner.GivenAsync("I am on a \"feature/123-test\" branch", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 21
        await testRunner.AndAsync("GPG signing is configured", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
        await testRunner.AndAsync("node_modules directory exists", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
        await testRunner.WhenAsync("I attempt to commit", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 24
        await testRunner.ThenAsync("the hook should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Require GPG signing configuration")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Pre-commit hook validation")]
        [global::Xunit.TraitAttribute("Description", "Require GPG signing configuration")]
        [global::Xunit.TraitAttribute("Category", "signed-commits")]
        public async global::System.Threading.Tasks.Task RequireGPGSigningConfiguration()
        {
            string[] tagsOfScenario = new string[] {
                    "signed-commits"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Require GPG signing configuration", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 27
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 28
        await testRunner.GivenAsync("node_modules directory exists", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 29
        await testRunner.AndAsync("I am on a \"feature/123-test\" branch", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
        await testRunner.AndAsync("GPG signing is not configured", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
        await testRunner.WhenAsync("I attempt to commit", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
        await testRunner.ThenAsync("the hook should fail with exit code 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 33
        await testRunner.AndAsync("the output should contain \"commit.gpgsign\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Accept commits with GPG signing enabled")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Pre-commit hook validation")]
        [global::Xunit.TraitAttribute("Description", "Accept commits with GPG signing enabled")]
        [global::Xunit.TraitAttribute("Category", "signed-commits")]
        public async global::System.Threading.Tasks.Task AcceptCommitsWithGPGSigningEnabled()
        {
            string[] tagsOfScenario = new string[] {
                    "signed-commits"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Accept commits with GPG signing enabled", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 36
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 37
        await testRunner.GivenAsync("I am on a \"feature/123-test\" branch", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 38
        await testRunner.AndAsync("GPG signing is configured", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
        await testRunner.AndAsync("node_modules directory exists", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
        await testRunner.WhenAsync("I attempt to commit", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
        await testRunner.ThenAsync("the hook should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Require node_modules to be installed")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Pre-commit hook validation")]
        [global::Xunit.TraitAttribute("Description", "Require node_modules to be installed")]
        [global::Xunit.TraitAttribute("Category", "prerequisites")]
        public async global::System.Threading.Tasks.Task RequireNode_ModulesToBeInstalled()
        {
            string[] tagsOfScenario = new string[] {
                    "prerequisites"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Require node_modules to be installed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 44
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 45
        await testRunner.GivenAsync("I am on a \"feature/123-test\" branch", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 46
        await testRunner.AndAsync("GPG signing is configured", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 47
        await testRunner.AndAsync("node_modules directory does not exist", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
        await testRunner.WhenAsync("I attempt to commit", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
        await testRunner.ThenAsync("the hook should fail with exit code 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 50
        await testRunner.AndAsync("the output should contain \"Dependencies not installed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await Pre_CommitHookValidationFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await Pre_CommitHookValidationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
