// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace McjCoderOrg.HookTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "pre-push")]
    public partial class Pre_PushHookValidationFeature : object, Xunit.IClassFixture<Pre_PushHookValidationFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "pre-push"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Pre-push hook validation", ("    As a developer\r\n    I want branch naming and tests validated before push\r\n   " +
                " So that the remote repository maintains quality standards"), global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PrePushHook.feature"
#line hidden
        
        public Pre_PushHookValidationFeature(Pre_PushHookValidationFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
    #line hidden
#line 8
        await testRunner.GivenAsync("I have a git repository with hooks configured", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 9
        await testRunner.AndAsync("node_modules directory exists", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Accept valid branch naming patterns")]
        [Xunit.TraitAttribute("FeatureTitle", "Pre-push hook validation")]
        [Xunit.TraitAttribute("Description", "Accept valid branch naming patterns")]
        [Xunit.TraitAttribute("Category", "branch-naming")]
        [Xunit.InlineDataAttribute("feature/123-login", new string[0])]
        [Xunit.InlineDataAttribute("fix/456-null-check", new string[0])]
        [Xunit.InlineDataAttribute("docs/789-readme", new string[0])]
        [Xunit.InlineDataAttribute("chore/101-cleanup", new string[0])]
        [Xunit.InlineDataAttribute("refactor/202-split", new string[0])]
        [Xunit.InlineDataAttribute("test/303-coverage", new string[0])]
        public async System.Threading.Tasks.Task AcceptValidBranchNamingPatterns(string branch, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "branch-naming"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("branch", branch);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Accept valid branch naming patterns", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 13
        await testRunner.GivenAsync(string.Format("I am on a \"{0}\" branch", branch), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 14
        await testRunner.WhenAsync("I attempt to push", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
        await testRunner.ThenAsync("the hook should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Allow push from main branch")]
        [Xunit.TraitAttribute("FeatureTitle", "Pre-push hook validation")]
        [Xunit.TraitAttribute("Description", "Allow push from main branch")]
        [Xunit.TraitAttribute("Category", "branch-naming")]
        public async System.Threading.Tasks.Task AllowPushFromMainBranch()
        {
            string[] tagsOfScenario = new string[] {
                    "branch-naming"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Allow push from main branch", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 28
        await testRunner.GivenAsync("I am on the \"main\" branch", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 29
        await testRunner.WhenAsync("I attempt to push", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 30
        await testRunner.ThenAsync("the hook should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Reject invalid branch name format")]
        [Xunit.TraitAttribute("FeatureTitle", "Pre-push hook validation")]
        [Xunit.TraitAttribute("Description", "Reject invalid branch name format")]
        [Xunit.TraitAttribute("Category", "branch-naming")]
        public async System.Threading.Tasks.Task RejectInvalidBranchNameFormat()
        {
            string[] tagsOfScenario = new string[] {
                    "branch-naming"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Reject invalid branch name format", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 34
        await testRunner.GivenAsync("I am on a \"my-feature\" branch", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 35
        await testRunner.WhenAsync("I attempt to push", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 36
        await testRunner.ThenAsync("the hook should fail", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 37
        await testRunner.AndAsync("the output should contain \"Invalid branch name\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Reject branch missing issue number")]
        [Xunit.TraitAttribute("FeatureTitle", "Pre-push hook validation")]
        [Xunit.TraitAttribute("Description", "Reject branch missing issue number")]
        [Xunit.TraitAttribute("Category", "branch-naming")]
        public async System.Threading.Tasks.Task RejectBranchMissingIssueNumber()
        {
            string[] tagsOfScenario = new string[] {
                    "branch-naming"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Reject branch missing issue number", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 40
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 41
        await testRunner.GivenAsync("I am on a \"feature/add-login\" branch", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 42
        await testRunner.WhenAsync("I attempt to push", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 43
        await testRunner.ThenAsync("the hook should fail", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 44
        await testRunner.AndAsync("the output should contain \"Invalid branch name\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Skip validation on detached HEAD")]
        [Xunit.TraitAttribute("FeatureTitle", "Pre-push hook validation")]
        [Xunit.TraitAttribute("Description", "Skip validation on detached HEAD")]
        [Xunit.TraitAttribute("Category", "ci-integration")]
        public async System.Threading.Tasks.Task SkipValidationOnDetachedHEAD()
        {
            string[] tagsOfScenario = new string[] {
                    "ci-integration"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Skip validation on detached HEAD", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 47
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 48
        await testRunner.GivenAsync("I am in detached HEAD state", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 49
        await testRunner.WhenAsync("I attempt to push", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 50
        await testRunner.ThenAsync("the hook should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 51
        await testRunner.AndAsync("the output should contain \"Detached HEAD\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Skip tests when solution file missing")]
        [Xunit.TraitAttribute("FeatureTitle", "Pre-push hook validation")]
        [Xunit.TraitAttribute("Description", "Skip tests when solution file missing")]
        [Xunit.TraitAttribute("Category", "test-execution")]
        public async System.Threading.Tasks.Task SkipTestsWhenSolutionFileMissing()
        {
            string[] tagsOfScenario = new string[] {
                    "test-execution"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Skip tests when solution file missing", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 54
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 55
        await testRunner.GivenAsync("no .sln file exists", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 56
        await testRunner.AndAsync("I am on a \"feature/123-test\" branch", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
        await testRunner.WhenAsync("I attempt to push", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 58
        await testRunner.ThenAsync("the hook should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Require node_modules to be installed")]
        [Xunit.TraitAttribute("FeatureTitle", "Pre-push hook validation")]
        [Xunit.TraitAttribute("Description", "Require node_modules to be installed")]
        [Xunit.TraitAttribute("Category", "prerequisites")]
        public async System.Threading.Tasks.Task RequireNode_ModulesToBeInstalled()
        {
            string[] tagsOfScenario = new string[] {
                    "prerequisites"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Require node_modules to be installed", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 61
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await this.FeatureBackgroundAsync();
#line hidden
#line 62
        await testRunner.GivenAsync("I am on a \"feature/123-test\" branch", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 63
        await testRunner.AndAsync("node_modules directory does not exist", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 64
        await testRunner.WhenAsync("I attempt to push", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 65
        await testRunner.ThenAsync("the hook should fail with exit code 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 66
        await testRunner.AndAsync("the output should contain \"Dependencies not installed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await Pre_PushHookValidationFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await Pre_PushHookValidationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
