//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace McjCoderOrg.ClaudeAutoResume.Resources;

using System.Globalization;
using System.Resources;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[System.Diagnostics.DebuggerNonUserCodeAttribute()]
[System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Strings
{
    private static ResourceManager? resourceMan;
    private static CultureInfo? resourceCulture;

    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Strings()
    {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static ResourceManager ResourceManager
    {
        get
        {
            if (resourceMan is null)
            {
                resourceMan = new ResourceManager("McjCoderOrg.ClaudeAutoResume.Resources.Strings", typeof(Strings).Assembly);
            }
            return resourceMan;
        }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    /// <summary>
    ///   Looks up a localized string similar to CLI tool to monitor Claude Code sessions and automatically resume on rate limits..
    /// </summary>
    internal static string AppDescription => ResourceManager.GetString("AppDescription", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to Claude Auto Resume Diagnostics.
    /// </summary>
    internal static string DiagnoseHeader => ResourceManager.GetString("DiagnoseHeader", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to OS: {OsDescription} ({Architecture}).
    /// </summary>
    internal static string DiagnoseOsInfo => ResourceManager.GetString("DiagnoseOsInfo", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to Runtime: .NET {DotNetVersion} ({RuntimeIdentifier}).
    /// </summary>
    internal static string DiagnoseRuntimeInfo => ResourceManager.GetString("DiagnoseRuntimeInfo", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to Log file: {LogPath}.
    /// </summary>
    internal static string ErrorLogLocation => ResourceManager.GetString("ErrorLogLocation", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to An unexpected error occurred. See log file for details..
    /// </summary>
    internal static string ErrorUnhandledException => ResourceManager.GetString("ErrorUnhandledException", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to Detected Session Limit Reached, resets at {ResetTime}.
    /// </summary>
    internal static string RateLimitDetected => ResourceManager.GetString("RateLimitDetected", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to Starting Claude Auto Resume v{AppVersion}.
    /// </summary>
    internal static string StartingApp => ResourceManager.GetString("StartingApp", resourceCulture) ?? string.Empty;

    /// <summary>
    ///   Looks up a localized string similar to Waiting {WaitMinutes} minutes for rate limit reset.
    /// </summary>
    internal static string WaitingForReset => ResourceManager.GetString("WaitingForReset", resourceCulture) ?? string.Empty;
}
